language: go

go:
  - 1.2
  - tip

before_install:
  - go get -v code.google.com/p/go.tools/cmd/cover
  - go get -v github.com/golang/lint/golint
  - export PATH=$PATH:$GOPATH/bin

script:
  - go test -v -cover ./...
  - echo $PATH
  - ls $GOPATH/bin
  - golint .